import type { AuctionOpportunity, DueDiligenceItem } from './domain'

export const opportunities: AuctionOpportunity[] = [
  {
    id: 'LEILAO-2026-0017',
    title: 'Apartamento — Belo Horizonte',
    assetType: 'Imóvel residencial',
    address: 'Rua dos Expedicionários, Pampulha',
    city: 'Belo Horizonte',
    state: 'MG',
    auctioneer: 'Leiloeira Modelo',
    status: 'pre_bid',
    currentBid: 218000,
    marketConservative: 390000,
    marketBase: 420000,
    marketOptimistic: 455000,
    maxBidAbsolute: 265000,
    maxBidRecommended: 250000,
    comfortBid: 230000,
    baseRoiPct: 34.8,
    score: 86,
    risk: 'Médio',
    confidence: 87,
    decision: 'B — Participar até limite',
    nextMilestone: 'Revisão final pré-lance',
    nextMilestoneDate: '2026-08-22T10:00:00-03:00',
    registrationNumber: '123.456',
    processNumber: '5000000-00.2026.8.13.0000',
    occupancyStatus: 'Ocupação não confirmada',
    paymentTerms: 'À vista em até 24 horas + comissão',
    mainRisk: 'Situação de ocupação ainda depende de confirmação documental.',
    mainUpside: 'Preço atual ainda está abaixo do lance de conforto.',
    blockers: ['Confirmar débitos condominiais', 'Atualizar matrícula antes do leilão'],
  },
  {
    id: 'LEILAO-2026-0018',
    title: 'Sala comercial — Contagem',
    assetType: 'Comercial',
    address: 'Centro Empresarial Eldorado',
    city: 'Contagem',
    state: 'MG',
    auctioneer: 'Central de Leilões',
    status: 'due_diligence',
    currentBid: 162000,
    marketConservative: 285000,
    marketBase: 310000,
    marketOptimistic: 335000,
    maxBidAbsolute: 188000,
    maxBidRecommended: 176000,
    comfortBid: 160000,
    baseRoiPct: 28.2,
    score: 78,
    risk: 'Médio',
    confidence: 73,
    decision: 'C — Monitorar',
    nextMilestone: 'Checar liquidez comercial',
    nextMilestoneDate: '2026-08-24T09:00:00-03:00',
    registrationNumber: '98.765',
    occupancyStatus: 'Desocupação não verificada',
    paymentTerms: 'Sinal + saldo em até 30 dias',
    mainRisk: 'Liquidez menor para salas comerciais na região.',
    mainUpside: 'Boa relação entre lance atual e valor conservador.',
    blockers: ['Validar taxa condominial', 'Comparáveis de venda insuficientes'],
  },
  {
    id: 'LEILAO-2026-0019',
    title: 'Casa — Nova Lima',
    assetType: 'Residencial',
    address: 'Condomínio fechado — região sul',
    city: 'Nova Lima',
    state: 'MG',
    auctioneer: 'Judicial Prime',
    status: 'valuation',
    currentBid: 355000,
    marketConservative: 620000,
    marketBase: 680000,
    marketOptimistic: 735000,
    maxBidAbsolute: 410000,
    maxBidRecommended: 385000,
    comfortBid: 350000,
    baseRoiPct: 41.5,
    score: 91,
    risk: 'Alto',
    confidence: 61,
    decision: 'C — Monitorar',
    nextMilestone: 'Revisar risco jurídico',
    nextMilestoneDate: '2026-08-26T15:00:00-03:00',
    occupancyStatus: 'Provavelmente ocupada',
    paymentTerms: 'À vista',
    mainRisk: 'Risco ocupacional e jurídico ainda alto para o patrimônio atual.',
    mainUpside: 'Alto spread entre avaliação conservadora e lance atual.',
    blockers: ['Parecer jurídico pendente', 'Custo de posse não estimado'],
  },
]

export const dueDiligenceItems: Record<string, DueDiligenceItem[]> = {
  'LEILAO-2026-0017': [
    { category: 'Documental', item: 'Edital analisado', status: 'confirmed', evidence: 'Edital salvo no Drive e dados principais extraídos.', risk: 'Baixo' },
    { category: 'Jurídico', item: 'Matrícula atualizada', status: 'warning', evidence: 'Matrícula existente, mas precisa atualização em D-3.', risk: 'Médio' },
    { category: 'Financeiro', item: 'Débitos condominiais', status: 'pending', evidence: 'Não confirmado pelo leiloeiro.', risk: 'Médio' },
    { category: 'Ocupação', item: 'Situação de posse', status: 'warning', evidence: 'Informação declarada, sem vistoria.', risk: 'Médio' },
  ],
  'LEILAO-2026-0018': [
    { category: 'Mercado', item: 'Comparáveis comerciais', status: 'pending', evidence: 'Amostra ainda pequena.', risk: 'Médio' },
    { category: 'Financeiro', item: 'Condomínio', status: 'pending', evidence: 'Solicitar boleto atualizado.', risk: 'Médio' },
  ],
}

export const pipeline = [
  { label: 'Novas', count: 8 },
  { label: 'Triagem', count: 12 },
  { label: 'Diligência', count: 5 },
  { label: 'Valuation', count: 3 },
  { label: 'Aprovadas', count: 2 },
]
